import { NextPage } from 'next'
import Head from 'next/head'
import { Containner } from './style'

const Login: NextPage = () => {
	return (
		<div>
			<Head>
				<title>featuring-apps</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Containner>Login</Containner>
		</div>
	)
}

export default Login
