import type { NextPage } from 'next'
import Head from 'next/head'


const Campaign: NextPage = () => {
  return (
    <>
    <div>
      <Head>
        <title>Campaign | featuring-apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Campaign</h1>
    </div>

    <style jsx>{`

        `}</style>
    </>
  )
}

export default Campaign