import type { NextPage } from 'next'
import Head from 'next/head'


const DashBoard: NextPage = () => {
  return (
    <>
  
      <div>
        <Head>
          <title>DashBoard | featuring-apps</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>DashBoard</h1>
      </div>

      <style jsx>{`

        `}</style>
        
    </>
  )
}

export default DashBoard