import type { NextPage } from 'next'
import Head from 'next/head'
import styles from "./styles.module.css"
//import Image from 'next/image'

const Login: NextPage = () => {
  return (
    <>
      <div>
        <Head>
          <title>featuring-apps</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Well come to featuring</h1>
      </div>

      <style jsx>{`

      `}</style>
    </>
  )
}

export default Login
