import type { NextPage } from 'next'
import Head from 'next/head'


const MyFAQ: NextPage = () => {
  return (
    <>
    <div>
      <Head>
        <title>MyFAQ | featuring-apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>MyFAQ</h1>
    </div>

    <style jsx>{`

        `}</style>
    </>
  )
}

export default MyFAQ