import { NextPage } from 'next'
import Head from 'next/head'
import { Containner } from "./style"

const MySetting: NextPage = () => {
  return (
    <div>
      <Head>
        <title>featuring-apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Containner>MySetting</Containner>
    </div>
  )
}

export default MySetting
